### ISSUE TITLE
Can you share the Cropped-PlantDoc dataset as well?

### ISSUE THREAD

**Issue by hammad-ilyas-umt** [pratikkayal/PlantDoc-Dataset#2]
I see that you achieved higher accuracy with cropped datsset. Can share that dataset as well?

**Comment by pratikkayal** [comment]
We have provided the images and the bounding boxes here: https://github.com/pratikkayal/PlantDoc-Object-Detection-Dataset

The cropped dataset can be obtained from this.

**Comment by hammad-ilyas-umt** [comment]
> We have provided the images and the bounding boxes here: https://github.com/pratikkayal/PlantDoc-Object-Detection-Dataset
> 
> The cropped dataset can be obtained from this.

ok thanks.
